### ISSUE TITLE
Metrics sent to splunk < 8 not working

### ISSUE THREAD

**Issue by dataPhysicist** [splunk/splunk-connect-for-ethereum#26]
--print-config shows     `multipleMetricFormatEnabled: false,`

trace output
```  ethlogger:eth:http:debug Sending JSON RPC batch containing 1 requests +3ms
  ethlogger:eth:http:trace Sending JSON RPC request over HTTP: [ { jsonrpc: '2.0', id: 20, method: 'eth_blockNumber', params: [] } ] +4ms
  ethlogger:hec:debug Flushing HEC queue for time limit being reached +80ms
  ethlogger:hec:debug Flushing HEC queue with 1 messages +1ms
  ethlogger:hec:debug Flushing HEC queue for time limit being reached +5ms
  ethlogger:hec:debug Flushing HEC queue with 4 messages +1ms
  ethlogger:eth:http:trace Received JSON RPC response:
  ethlogger:eth:http:trace [ { jsonrpc: '2.0', result: '0x7df322', id: 20 } ] +9ms
  ethlogger:eth:http:debug Completed JSON RPC request in 9 ms +9ms
  ethlogger:blockwatcher:debug Received latest block number: 8254242 +74ms
  ethlogger:blockwatcher:debug Found 0 block ranges to process +0ms
  ethlogger:hec:trace Compressed batch of HEC messages from 828 bytes -> 453 bytes +0ms
  ethlogger:hec:trace Compressed batch of HEC messages from 1630 bytes -> 361 bytes +3ms
  ethlogger:hec:debug Successfully flushed 1 HEC messages in 1 attempts and 15 ms +9ms
  ethlogger:hec:debug Response from HEC: {"text":"Incorrect index","code":7,"invalid-event-number":1} +2ms
  ethlogger:hec:debug Failed to send batch to HEC (attempt 1) Error: HEC responded with status 400
    at HecClient.sendToHec (/ethlogger/lib/hec.js:361:27)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) +0ms
  ethlogger:hec:error Failed to send batch to HEC (attempt 1): Error: HEC responded with status 400 +0ms
```

adding `--no-collect-node-metrics` to the docker run successfully sends events. 

Splunk Enterprise
Version: `7.2.5.1`
Build: `962d9a8e1586`

**Comment by ziegfried** [comment]
I wasn't able to reproduce with a similar Splunk version (7.2.10.1). It seem likely this was a different issue at the time. We'll have integration tests asserting HEC client compatibility with a set of different Splunk versions (including 7.2.10.1) with the new HEC client library (currently in a private repo, to be released soon).

Closing this issue for now. Let's reopen if find a way to reproduce.
