### ISSUE TITLE
Geth-specific metrics not collected

### ISSUE THREAD

**Issue by j4ys0n** [splunk/splunk-connect-for-ethereum#49]
When connected to a geth or quorum node ethlogger continually reports the following error:
```
2020-06-10T21:34:23.624Z ethlogger:nodestats:error Failed to collect node metrics (35 consecutive failures): JsonRpcError: the method debug_metrics does not exist/is not available
    at Object.checkError (/ethlogger/lib/eth/jsonrpc.js:31:15)
    at Object.callback (/ethlogger/lib/eth/client.js:114:35)
    at executeBatchRequest (/ethlogger/lib/eth/client.js:24:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Timeout.BatchedEthereumClient.processQueue (/ethlogger/lib/eth/client.js:97:20) {
  code: -32601,
  data: undefined
}
```

geth docs: https://geth.ethereum.org/docs/rpc/ns-debug

**Comment by atoulme** [comment]
I found the commit where this was removed: https://github.com/ethereum/go-ethereum/commit/29bc982d75d498e902b901caaac1a82a205a6cb1#diff-3e693b632c1db48405aabd1a0715483b

**Comment by j4ys0n** [comment]
Looks like this applies to geth 1.9.0+ and quorum 2.6+
